# Site settings
title: 无敌大泡泡
url:  "https://wudidapaopao.github.io"
baseurl: "/"
author:
  name: "无敌大泡泡"
  email: "664920313@qq.com"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://www.github.com/wudidapaopao
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never
